import { Leaf, Shield, Train, Landmark, CloudSun, HeartPulse, Home, GraduationCap, HandHeart, Ticket } from 'lucide-react';
import type { DashboardConfig } from '@/types/dashboard';

export const DASHBOARDS: DashboardConfig[] = [
  {
    id: 'environment',
    title: 'Environment',
    shortTitle: 'Environment',
    description: 'Flood warnings, air quality, and carbon intensity monitoring',
    href: '/environment',
    icon: Leaf,
    color: 'text-green-600',
    bgColor: 'bg-green-50',
    available: true,
  },
  {
    id: 'weather',
    title: 'Weather',
    shortTitle: 'Weather',
    description: 'Current conditions, 7-day forecast, and weather alerts',
    href: '/weather',
    icon: CloudSun,
    color: 'text-sky-600',
    bgColor: 'bg-sky-50',
    available: true,
  },
  {
    id: 'crime',
    title: 'Crime & Safety',
    shortTitle: 'Crime',
    description: 'Crime data across BN1–BN43, category breakdowns, and policing',
    href: '/crime',
    icon: Shield,
    color: 'text-blue-600',
    bgColor: 'bg-blue-50',
    available: true,
  },
  {
    id: 'transport',
    title: 'Transport',
    shortTitle: 'Transport',
    description: 'Live train departures, delays, and disruption alerts',
    href: '/transport',
    icon: Train,
    color: 'text-amber-600',
    bgColor: 'bg-amber-50',
    available: true,
  },
  {
    id: 'planning',
    title: 'Planning & Development',
    shortTitle: 'Planning',
    description: 'Planning applications and development activity',
    href: '/planning',
    icon: Landmark,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-50',
    available: true,
  },
  {
    id: 'health',
    title: 'Health & NHS',
    shortTitle: 'Health',
    description: 'GP practices, pharmacies, hospitals, and dentists near Brighton',
    href: '/health',
    icon: HeartPulse,
    color: 'text-pink-600',
    bgColor: 'bg-pink-50',
    available: true,
  },
  {
    id: 'housing',
    title: 'Housing & Property',
    shortTitle: 'Housing',
    description: 'Property prices, trends, and housing market data for Brighton & Hove',
    href: '/housing',
    icon: Home,
    color: 'text-teal-600',
    bgColor: 'bg-teal-50',
    available: true,
  },
  {
    id: 'schools',
    title: 'Schools & Education',
    shortTitle: 'Schools',
    description: 'Schools and educational facilities in Brighton & Hove',
    href: '/schools',
    icon: GraduationCap,
    color: 'text-violet-600',
    bgColor: 'bg-violet-50',
    available: true,
  },
  {
    id: 'community',
    title: 'Community & Food Banks',
    shortTitle: 'Community',
    description: 'Food banks, urgent needs, and community support near Brighton',
    href: '/community',
    icon: HandHeart,
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-50',
    available: true,
  },
  {
    id: 'entertainment',
    title: 'Entertainment',
    shortTitle: 'Events',
    description: 'Concerts, shows, theatre, comedy, exhibitions, and events in Brighton',
    href: '/entertainment',
    icon: Ticket,
    color: 'text-rose-600',
    bgColor: 'bg-rose-50',
    available: true,
  },
];

export function getDashboard(id: string): DashboardConfig | undefined {
  return DASHBOARDS.find((d) => d.id === id);
}
