/**
 * Static TIPLOC -> station name map for Brighton-area routes.
 * Covers the Brighton Main Line, Coastway East/West, Arun Valley,
 * and key London termini. Unknown TIPLOCs fall back to the code itself.
 */
export const TIPLOC_NAMES: Record<string, string> = {
  // Brighton
  BRGHTN: 'Brighton',
  PRSPK: 'Preston Park',
  PRSP: 'Preston Park',

  // Brighton Main Line (northbound to London)
  HASSKS: 'Hassocks',
  BRGSHL: 'Burgess Hill',
  BURGESH: 'Burgess Hill',  // alternative TIPLOC
  WVSFLD: 'Wivelsfield',
  HYWRDSH: 'Haywards Heath',
  HAYWHTH: 'Haywards Heath',
  BALCMBE: 'Balcombe',
  THBDGS: 'Three Bridges',
  CRWLY: 'Crawley',
  IFIELD: 'Ifield',
  FAYGATE: 'Faygate',
  GTWARAP: 'Gatwick Airport',
  HORLEY: 'Horley',
  SALFRDS: 'Salfords',
  REDHILL: 'Redhill',
  MERSTAM: 'Merstham',
  CTHMJN: 'Coulsdon Town',
  PURLEY: 'Purley',
  ECROYDN: 'East Croydon',
  CLPHMJC: 'Clapham Junction',
  BALHM: 'Balham',
  NRWDJN: 'Norwood Junction',
  SELHURS: 'Selhurst',
  THORTNH: 'Thornton Heath',
  CRYSTLP: 'Crystal Palace',
  SYDENHM: 'Sydenham',
  PECKRYE: 'Peckham Rye',
  TULSEH: 'Tulse Hill',
  STRTHMH: 'Streatham Hill',
  STRETHM: 'Streatham',
  MITCHJN: 'Mitcham Junction',
  HACKBDG: 'Hackbridge',
  CSDNJRD: 'Carshalton',
  SUTTON: 'Sutton',

  // London termini and central
  VICTRIA: 'London Victoria',
  LNDBRDG: 'London Bridge',
  LNDNBDE: 'London Bridge',
  BLKFRRS: 'London Blackfriars',
  KNGX: 'London Kings Cross',
  STPX: 'London St Pancras',
  FARNGDN: 'Farringdon',
  CTYTHML: 'City Thameslink',
  WATRLMN: 'London Waterloo',
  EUSTON: 'London Euston',
  PADTON: 'London Paddington',
  CHRX: 'London Charing Cross',
  CANLST: 'London Cannon Street',
  LIVST: 'London Liverpool Street',
  MRGT: 'London Marylebone',
  FCHST: 'London Fenchurch Street',

  // Coastway West (Brighton -> Portsmouth/Southampton)
  HOVE: 'Hove',
  ALDRNGT: 'Aldrington',
  PRTSLD: 'Portslade',
  FSHRSG: 'Fishersgate',
  STHWICK: 'Southwick',
  SHRHM: 'Shoreham-by-Sea',
  LANCNG: 'Lancing',
  ETWRTHG: 'East Worthing',
  WRTHNG: 'Worthing',
  WTWRTHG: 'West Worthing',
  DRRNGS: 'Durrington-on-Sea',
  GORINGS: 'Goring-by-Sea',
  ANGMRNG: 'Angmering',
  FRDNJN: 'Ford',
  FORD: 'Ford',
  BARNHAM: 'Barnham',
  LITTLEH: 'Littlehampton',
  LTLHMJN: 'Littlehampton',  // junction TIPLOC
  LTLHMPT: 'Littlehampton',  // alternative TIPLOC
  ARNDEL: 'Arundel',
  AMBRLY: 'Amberley',
  PLBRGH: 'Pulborough',
  BLLNGSHR: 'Billingshurst',
  CHRSTSH: 'Christ\'s Hospital',
  HORSHAM: 'Horsham',
  BOGNRGS: 'Bognor Regis',
  CHCHSTR: 'Chichester',
  HVNT: 'Havant',
  FAREHAM: 'Fareham',
  FRATTON: 'Fratton',
  PRTSSEA: 'Portsmouth & Southsea',
  PRTSMHR: 'Portsmouth Harbour',
  SOTON: 'Southampton Central',
  SOTNCNL: 'Southampton Central',
  COSHAM: 'Cosham',
  PORTCJN: 'Portcreek Junction',
  HILSEA: 'Hilsea',

  // Coastway East (Brighton -> Eastbourne/Hastings)
  LRDNRD: 'London Road (Brighton)',
  BRGHLRD: 'London Road (Brighton)',
  MLSCMB: 'Moulsecoomb',
  FALMER: 'Falmer',
  LEWES: 'Lewes',
  GLYNDE: 'Glynde',
  BRWICK: 'Berwick',
  PLGATE: 'Polegate',
  HMPDNPK: 'Hampden Park',
  EBOURNJ: 'Eastbourne',
  EBOURNE: 'Eastbourne',
  BXHILL: 'Bexhill',
  BXHLL: 'Bexhill',
  STLNWSQ: 'St Leonards Warrior Square',
  HSTNGS: 'Hastings',
  ORE: 'Ore',
  COODEN: 'Cooden Beach',
  COLNGTN: 'Collington',
  NORMNSB: 'Normans Bay',
  PVNSYBY: 'Pevensey Bay',
  PVNSEY: 'Pevensey & Westham',

  // East Coastway branch (Seaford)
  SFRD: 'Seaford',
  NWHVNTW: 'Newhaven Town',
  NWHVNHR: 'Newhaven Harbour',
  BISHPST: 'Bishopstone',

  // Arun Valley / other
  DORKING: 'Dorking',
  DRKINGD: 'Dorking Deepdene',
  LTHRHD: 'Leatherhead',
  EPSOM: 'Epsom',
  WDON: 'Wimbledon',
  CHSSTED: 'Chipstead',

  // Thameslink corridor
  LUTON: 'Luton',
  LUTNAPT: 'Luton Airport Parkway',
  STALBC: 'St Albans City',
  BEDFDM: 'Bedford',
  WHMPSTN: 'West Hampstead Thameslink',
  KENTSHTW: 'Kentish Town',
  ELEPH: 'Elephant & Castle',
  LONBRDJ: 'London Bridge',
  HARPNDJ: 'Harpenden',
  RADLETT: 'Radlett',
  ELSTREE: 'Elstree & Borehamwood',
  MILLHLB: 'Mill Hill Broadway',
  HENDON: 'Hendon',
  CRICKLW: 'Cricklewood',
  STNBRAJ: 'Stonebridge Park',
  LEAGRVE: 'Leagrave',
  FLTWLL: 'Flitwick',
  HRPNDN: 'Harpenden',
  LTNBZPK: 'Luton Airport Parkway',

  // Additional Southern/Thameslink stops
  LATCHMR: 'Latchmere Junction',
  BTRSAPK: 'Battersea Park',
  WANDSWRC: 'Wandsworth Common',
  CLDNSTH: 'Coulsdon South',
  SNDRSTD: 'Sanderstead',
  OXTED: 'Oxted',
  HRSTGRN: 'Hurst Green',
  EGHM: 'East Grinstead',

  // South Western stops (sometimes in Brighton area data)
  GUILDFD: 'Guildford',
  WOKING: 'Woking',
  BASNGSK: 'Basingstoke',
  WINCHST: 'Winchester',
  EASTLGH: 'Eastleigh',
  FRNBORO: 'Farnborough',
  FLEETSS: 'Fleet',
  BRKNHST: 'Brockenhurst',
  BORNMTH: 'Bournemouth',
  POOLE: 'Poole',
  SALISBR: 'Salisbury',
  READING: 'Reading',

  // Southeastern (sometimes visible via Thameslink)
  SEVENKS: 'Sevenoaks',
  TONBDG: 'Tonbridge',
  ASHFKY: 'Ashford International',
  MAIDSTW: 'Maidstone West',
  MAIDSTE: 'Maidstone East',
  CHATHAM: 'Chatham',
  GLLNGHM: 'Gillingham',
  ROFSTR: 'Rochester',
  STROOD: 'Strood',
  DARTFD: 'Dartford',
};

export function getStationName(tiploc: string): string {
  return TIPLOC_NAMES[tiploc] ?? tiploc;
}
